---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts: ${ES_HOST:127.0.0.1}
  port: ${ES_PORT:9200}
  url_prefix: ${ES_URL_PREFIX}
  use_ssl: ${ES_SSL:False}
  certificate: ${ES_CA_CERT}
  client_cert: ${ES_CLIENT_CERT}
  client_key: ${ES_CLIENT_KEY}
  ssl_no_validate: ${ES_SSL_NO_VERIFY:False}
  http_auth: ${ES_HTTP_AUTH}
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
